version: '3.3'

services:
  arangodb:
    container_name: arangodb
    image: arangodb:3.8.4
    platform: linux/x86_64
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGODB_ROOT_PASSWORD:-admin}
    volumes:
      - arangodb:/var/lib/arangodb3
    ports:
      - "8529:8529"
    networks:
      - arangodb
    restart: unless-stopped

  app:
    build: .
    container_name: app
    image: pathao:latest
    depends_on:
      - arangodb
    volumes:
      - ./config.yaml:/etc/pathao/config.yaml
    ports:
      - 8080:8080
    networks:
      - arangodb
    links:
      - arangodb
    command: 'serve --config /etc/pathao/config.yaml'
    restart: unless-stopped

networks:
  arangodb:
    driver: bridge
volumes:
  arangodb:

