name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/suaas21/pathao
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up git config
        run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        env:
          GOPATH: /home/go/

      - name: Run the project with databases
        run: |
          make serve
          sleep 180s
      - name: test api server ok
        run: |
          curl --request GET --url http://localhost:8080/api/v1/public/ok --header 'Content-Type: application/json'
          
          
          
